spring:
  application:
    name: datn
  datasource:
    url: jdbc:mariadb://210.211.101.27:5019/TienSchema1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: quiPIgINaBLe
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
